### ISSUE TITLE
Error linked to the -t flag

### ISSUE THREAD

**Issue by baileyp1** [uym2/TreeShrink#22]
Hello, I think I found an error connected to the -t flag and when I was trying to use the -i, -t and -a flags together.

run_treeshrink.py complained about the treeExt variable not being defined. Looking inside the code, line ~260 is commented out:
treeName,treeExt = splitext(args["tree"])
but treeExt is still being used on the next line. I uncommented the line, recompiled and the error went away. The script has been modified since I downloaded the repo it but I think the error still applies.
Best wishes

Paul B.

**Comment by uym2** [comment]
Thank you very much for pointing this out. Fixed in the new version 1.3.4.
