### ISSUE TITLE
run_treeshrink.py fails with python 3.10

### ISSUE THREAD

**Issue by nylander** [uym2/TreeShrink#33]
FYK,

After a recent local upgrade of my Ubuntu Linux OS --- which brought python to version 3.10.4 --- `run_treeshrink.py` no longer works.

The reason seems to be an outdated version of dendropy's file `utility/container.py` in the TreeShrink repo. Apparently, there was a change between python 3.9 and 3.10 involving the library `collections` (see, e.g., <https://www.datasciencelearner.com/attributeerror-module-collections-has-no-attribute-mutablemapping/>, and <https://github.com/jeetsukumaran/DendroPy/blob/main/src/dendropy/utility/container.py>).

Some details:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
$ python -V
Python 3.10.4
$ git clone https://github.com/uym2/TreeShrink.git
$ cd TreeShrink
$ python setup.py install --user
$  python run_treeshrink.py 
Traceback (most recent call last):
  File "/home/nylander/tmp/TreeShrink/run_treeshrink.py", line 5, in <module>
    from treeshrink.optimal_filter_lib import TreeFilter
  File "/home/nylander/tmp/TreeShrink/treeshrink/optimal_filter_lib.py", line 2, in <module>
    from dendropy.datamodel.treemodel import Tree
  File "/home/nylander/tmp/TreeShrink/dendropy/__init__.py", line 24, in <module>
    from dendropy.dataio.nexusprocessing import get_rooting_argument
  File "/home/nylander/tmp/TreeShrink/dendropy/dataio/__init__.py", line 20, in <module>
    from dendropy.dataio import newickreader
  File "/home/nylander/tmp/TreeShrink/dendropy/dataio/newickreader.py", line 29, in <module>
    from dendropy.dataio import nexusprocessing
  File "/home/nylander/tmp/TreeShrink/dendropy/dataio/nexusprocessing.py", line 30, in <module>
    from dendropy.utility import container
  File "/home/nylander/tmp/TreeShrink/dendropy/utility/container.py", line 356, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by V-Z** [comment]
My easy PR https://github.com/uym2/TreeShrink/pull/40 should fix it. You can try it.

**Comment by uym2** [comment]
Thank you very much for pointing out the error snf fixing it. I will do
some tests and will merge.

**Comment by smirarab** [comment]
ping!

**Comment by chrisjackson-pellicle** [comment]
Hi - won't this PR break compatibility with Python <= 3.9, though?  

In the link provided in the opening post (https://www.datasciencelearner.com/attributeerror-module-collections-has-no-attribute-mutablemapping/), solution #2 suggests a dynamic approach i.e.:

```
import collections 
if sys.version_info.major == 3 and sys.version_info.minor >= 10

    from collections.abc import MutableMapping
else 
    from collections import MutableMapping
```

Then, [`CaseInsensitiveDict(collections.MutableMapping)`](https://github.com/uym2/TreeShrink/blob/825e633e081cb7c17024f32be952c5d1e4bdf9e0/dendropy/utility/container.py#L356) can be changed to `CaseInsensitiveDict(MutableMapping)`. It should then work with e.g. either Python 3.9 or 3.10.

Cheers,

Chris

**Comment by nylander** [comment]
Hi,
for the dendropy code shipped with TreeShrink, the code suggested by  @chrisjackson-pellicle will work given that `sys` is imported before checking for version and after adding the missing colons for the pythonic `if:` `else:` :-)
I would have liked to see the whole dendropy folder updated though. Most probably more work...
Cheers
Johan
> 
> ```
>import sys
>import collections 
> if sys.version_info.major == 3 and sys.version_info.minor >= 10:
>     from collections.abc import MutableMapping
> else: 
>     from collections import MutableMapping
> ```
> 
> Then, [`CaseInsensitiveDict(collections.MutableMapping)`](https://github.com/uym2/TreeShrink/blob/825e633e081cb7c17024f32be952c5d1e4bdf9e0/dendropy/utility/container.py#L356) can be changed to `CaseInsensitiveDict(MutableMapping)`. It should then work with e.g. either Python 3.9 or 3.10.
>
