### ISSUE TITLE
IndexError due to double backslash windows directories.

### ISSUE THREAD

**Issue by AshtonPooley** [uym2/TreeShrink#41]
Due to Windows using double backslash and the recursive list dir function assuming directories use a single forward slash the following exception is caused during installation

`Traceback (most recent call last):
  File "D:\GitHub\TreeShrink\setup.py", line 25, in <module>
    'package_data':{'':recursive_list_dir('Rlib')+recursive_list_dir('R_scripts')},
  File "D:\GitHub\TreeShrink\setup.py", line 14, in recursive_list_dir
    listing.append(z.split(path+'/')[1])
IndexError: list index out of range`

**Comment by uym2** [comment]
Merged. I am thankful for the fix!
