### ISSUE TITLE
Argument issues in examples?

### ISSUE THREAD

**Issue by mkweskin** [uym2/TreeShrink#8]
I'm new to your program and just trying it out, but I think the arguments in the examples in the README.md are out of date.

For example:

- `run_treeshrink.py  -i test_data/mm10.trees` doesn't work, but this works: `run_treeshrink.py  -t test_data/mm10.trees`

- Same thing with this example. `run_treeshrink.py  -i test_data/mm10.trees -q "0.05 0.10" -d test_data/mm10_treeshrink_multi` doesn't work, but this works `run_treeshrink.py  -t test_data/mm10.trees -q "0.05 0.10" -o test_data/mm10_treeshrink_multi`

Thanks 👍

**Comment by uym2** [comment]
We are thankful for your notice on this. We updated the README so that it is consistent with the program behavior. Please let us know should you find further problems.
